version: '3.9'

services:

  selenoid:
    image: aerokube/selenoid
    container_name: selenoid
    command: -listen :4444 -limit 10 -conf /etc/selenoid/browsers.json -video-output-dir /opt/selenoid/video/ -timeout 3m0s
    ports:
      - "4444:4444"
    volumes:
      - "$PWD:/etc/selenoid/"
      - "/var/run/docker.sock:/var/run/docker.sock"
    network_mode: "bridge"

  selenoid-ui:
    image: aerokube/selenoid-ui
    container_name: selenoid-ui
    links:
      - selenoid
    ports:
      - "8081:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
    network_mode: "bridge"

  maven:
    build:
      context: image/maven
    container_name: maven
    network_mode: "bridge"
    volumes:
      - .:/app
    working_dir: /app
    #    depends_on:
    #      - selenoid-chrome
    links:
      - selenoid
    #      - selenoid-chrome
    command: ["mvn", "clean", "test"]
